### ISSUE TITLE
Word Detail page

### ISSUE THREAD

**Issue by reline** [reline/Jisho#18]
Show extended descriptions/explanations for words, maybe include example sentences and names related to the word.

**Comment by surajsau** [comment]
Example sentences is another problem. They've taken it from Tatoeba which is a 125MB file. I guess it has to be hosted in the backend or we need to wait for API enhancement

**Comment by Reline** [comment]
Originally I was hitting the Jisho web pages and parsing the HTML for this, real nasty stuff. This is definitely a backlog item.
