### ISSUE TITLE
Offline use

### ISSUE THREAD

**Issue by reline** [reline/Jisho#20]
"Nice app for a great website, but doesn't work offline. Was looking for something to use in Japan, where I don't have data and often am not on WiFi since Google Translate sucks."

"I don't really see a reason to use the app. Maybe if it offered offline search or something."

"I would like to see an option to download the dictionary for offline use."

**Comment by surajsau** [comment]
@Reline can I use Realm DB to help out with the Offline use ?

**Comment by Reline** [comment]
👍  Sure thing, Realm is my ORM of choice so feel free to push up some work on a branch and I can help out.

**Comment by Reline** [comment]
How were you planning on approaching this, by the way?

**Comment by surajsau** [comment]
Since jisho uses JMDict Tatoeba etc. which have data dumps. I guess using them can come handy. Still working on how to implement search.

**Comment by surajsau** [comment]
Maybe we can keep a separate option for offline support. When the user clicks on it, then we can download the data dumps in background

**Comment by Reline** [comment]
Yeah, the search is the most difficult to tackle because we would have to imitate the same results as the Jisho API. 

I agree, there should be an option to download for offline mode instead of forcibly downloading it all immediately.

I want to integrate an option to save favorites as well #19 so I'll start up the realm integration on a new branch and once that's done we can start writing for these features on separate branches.

**Comment by surajsau** [comment]
yes. Makes sense. Meanwhile I can take up some other issues.

**Comment by Reline** [comment]
I've taken the liberty of starting to set up models to parse the JMDict XML files and their kanji lookup files. I'll convert the dictionary models into the API models, then just insert them into the realm DB and either place that on my server or serve the app to the store with the DB preinstalled. Search queries should just do word, reading, and glossary lookups.

**Comment by Reline** [comment]
Taking this into a different direction, I've noticed Realm is hard to manage in other projects so I'll be building a SQLite database outside the Android environment then downloading from a server at runtime. Probably using SQLBrite/SQLDelight for interfacing.

**Comment by reline** [comment]
Finally got english definitions and parts of speech showing after #48 was merged, needs some performance improvements however.
Last but not least is proper okurigana support, currently the readings are not aligned with the kanji.
